spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ocrdb
    username: ocruser
    password: ocrpass
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    # 클러스터링을 위한 설정
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 1.0
    # 연결 실패 시 재시도 설정
    connection-timeout: 60000
    requested-heartbeat: 60

# 프로파일별 설정
---
spring:
  config:
    activate:
      on-profile: cluster
  rabbitmq:
    # 클러스터 모드에서는 HAProxy를 통해 연결
    host: localhost
    port: 5671
    username: admin
    password: admin123
    # 클러스터 노드들 (HAProxy 없이 직접 연결 시)
    # addresses: localhost:5672,localhost:5673,localhost:5674
